export const ApiPath = {
    API: '/api',
    ROOT: '/',
    AUTH: '/auth',
    SIGN_IN: '/sign-in',
    SIGN_UP: '/sign-up',
    USER: '/user',
    USERS: '/users',
    WALLETS: '/wallets',
    TRANSACTIONS: '/transactions',
    CATEGORIES: '/categories',
    IMPORT_FROM_CSV: '/import-from-csv',
    EXPORT_TO_CSV: '/export-to-csv',
    DIVERSIFICATION: '/diversification',
    IMPORT_FROM_ETHERSCAN: '/import-from-etherscan',
} as const;
