import { Header } from "@/components/Header";
import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import './globals.css'
import { ClientProvider } from "@/components/ClientProviders";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <ClientProvider>
          <Header/>
          <main className="p-8">
            {children}
          </main>
        </ClientProvider>
      </body>
    </html>
  );
}
